import { Word, Segment } from "./fx";

export const CAPTIONS: Record<string, Word[]> = {
  "hook": [
    { "text": "this", "timestamp": [0.0, 0.32] },
    { "text": "pull", "timestamp": [0.32, 0.64] },
    { "text": "request", "timestamp": [0.64, 0.96] },
    { "text": "was", "timestamp": [0.96, 1.2] },
    { "text": "opened", "timestamp": [1.2, 1.44] },
    { "text": "by", "timestamp": [1.44, 1.68] },
    { "text": "a", "timestamp": [1.68, 1.84] },
    { "text": "swipe", "timestamp": [1.84, 2.24] },
  ],
  "problem": [
    { "text": "your", "timestamp": [0.0, 0.4] },
    { "text": "backlog", "timestamp": [0.4, 0.96] },
    { "text": "is", "timestamp": [0.96, 1.36] },
    { "text": "rotting", "timestamp": [1.36, 1.84] },
  ],
  "product1": [
    { "text": "doomscrum", "timestamp": [0.0, 0.8] },
    { "text": "turns", "timestamp": [0.8, 1.2] },
    { "text": "it", "timestamp": [1.2, 1.36] },
    { "text": "into", "timestamp": [1.36, 1.6] },
    { "text": "a", "timestamp": [1.6, 1.76] },
    { "text": "feed", "timestamp": [1.76, 2.08] },
  ],
  "product2": [
    { "text": "swipe", "timestamp": [0.16, 0.56] },
    { "text": "right", "timestamp": [0.56, 0.88] },
    { "text": "to", "timestamp": [0.88, 1.04] },
    { "text": "ship", "timestamp": [1.04, 1.68] },
    { "text": "swipe", "timestamp": [1.68, 2.16] },
    { "text": "left", "timestamp": [2.16, 2.72] },
    { "text": "to", "timestamp": [2.72, 2.96] },
    { "text": "skip", "timestamp": [2.96, 3.52] },
  ],
  "swipe": [
    { "text": "swipe", "timestamp": [0.16, 0.64] },
    { "text": "right", "timestamp": [0.64, 1.28] },
    { "text": "agent", "timestamp": [1.6, 1.92] },
    { "text": "cooks", "timestamp": [1.92, 2.4] },
    { "text": "it", "timestamp": [2.4, 2.88] },
    { "text": "pull", "timestamp": [3.12, 3.52] },
    { "text": "request", "timestamp": [3.52, 4.0] },
    { "text": "opened", "timestamp": [4.0, 4.48] },
  ],
  "price": [
    { "text": "three", "timestamp": [0.0, 0.32] },
    { "text": "cents", "timestamp": [0.32, 0.64] },
    { "text": "a", "timestamp": [0.64, 0.8] },
    { "text": "clip", "timestamp": [0.8, 1.36] },
    { "text": "operators", "timestamp": [1.44, 2.0] },
    { "text": "are", "timestamp": [2.0, 2.24] },
    { "text": "standing", "timestamp": [2.24, 2.56] },
    { "text": "by", "timestamp": [2.56, 2.88] },
  ],
  "cta": [
    { "text": "brew", "timestamp": [0.0, 0.4] },
    { "text": "install", "timestamp": [0.4, 0.8] },
    { "text": "doom", "timestamp": [0.8, 1.2] },
    { "text": "scrum", "timestamp": [1.2, 1.84] },
    { "text": "your", "timestamp": [1.84, 2.16] },
    { "text": "backlog", "timestamp": [2.16, 2.48] },
    { "text": "is", "timestamp": [2.48, 2.72] },
    { "text": "waiting", "timestamp": [2.72, 3.04] },
  ],
};

export const SEGMENTS: Record<string, Segment[]> = {};
